"""I forgot if mappers need a revision or not

Revision ID: 9dcf23622325
Revises: a109a2703a1b
Create Date: 2026-06-22 16:44:36.035363

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9dcf23622325"
down_revision: str | None = "a109a2703a1b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "monitored_urls",
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=True),
        sa.Column("check_interval", sa.Integer(), nullable=False),
        sa.Column("selector_ignore", sa.Text(), nullable=True),
        sa.Column("is_active", sa.String(length=1), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_table(
        "assets",
        sa.Column("monitored_url_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=True),
        sa.Column("warc_storage_key", sa.String(length=2048), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["monitored_url_id"], ["monitored_urls.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("monitored_url_id", "content_hash", name="uq_snapshot_url_hash"),
    )
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_assets_content_hash"), ["content_hash"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_assets_monitored_url_id"), ["monitored_url_id"], unique=False
        )

    op.create_table(
        "snapshots",
        sa.Column("monitored_url_id", sa.UUID(), nullable=False),
        sa.Column("text_content", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["monitored_url_id"], ["monitored_urls.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("monitored_url_id", "content_hash", name="uq_snapshot_url_hash"),
    )
    with op.batch_alter_table("snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_snapshots_content_hash"), ["content_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_snapshots_monitored_url_id"), ["monitored_url_id"], unique=False
        )

    op.create_table(
        "snapshot_assets",
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["snapshot_id"], ["snapshots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("snapshot_assets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_snapshot_assets_asset_id"), ["asset_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_snapshot_assets_snapshot_id"), ["snapshot_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("snapshot_assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_snapshot_assets_snapshot_id"))
        batch_op.drop_index(batch_op.f("ix_snapshot_assets_asset_id"))

    op.drop_table("snapshot_assets")
    with op.batch_alter_table("snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_snapshots_monitored_url_id"))
        batch_op.drop_index(batch_op.f("ix_snapshots_content_hash"))

    op.drop_table("snapshots")
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_assets_monitored_url_id"))
        batch_op.drop_index(batch_op.f("ix_assets_content_hash"))

    op.drop_table("assets")
    op.drop_table("monitored_urls")
    # ### end Alembic commands ###
