"""Decouple assets from snapshots

Revision ID: a109a2703a1b
Revises: 2fd0d7f0ef3b
Create Date: 2026-06-22 09:50:50.429449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a109a2703a1b'
down_revision: Union[str, None] = '2fd0d7f0ef3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('snapshotassets',
    sa.Column('snapshot_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('snapshotassets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snapshotassets_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_snapshotassets_snapshot_id'), ['snapshot_id'], unique=False)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('monitored_url_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('monitored_urls', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)

    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.alter_column('monitored_url_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.drop_column('warc_storage_key')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warc_storage_key', sa.VARCHAR(length=2048), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('monitored_url_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('monitored_urls', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
        batch_op.alter_column('monitored_url_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('snapshotassets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snapshotassets_snapshot_id'))
        batch_op.drop_index(batch_op.f('ix_snapshotassets_asset_id'))

    op.drop_table('snapshotassets')
    # ### end Alembic commands ###
