"""Initial revision

Revision ID: b86eada17e54
Revises:
Create Date: 2026-05-19 10:41:06.024943

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b86eada17e54"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "monitored_urls",
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=True),
        sa.Column("check_interval", sa.Integer(), nullable=False),
        sa.Column("selector_ignore", sa.Text(), nullable=True),
        sa.Column("is_active", sa.String(length=1), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_table(
        "snapshots",
        sa.Column("monitored_url_id", sa.UUID(), nullable=False),
        sa.Column("raw_html", sa.Text(), nullable=True),
        sa.Column("text_content", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["monitored_url_id"], ["monitored_urls.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("monitored_url_id", "content_hash", name="uq_snapshot_url_hash"),
    )
    with op.batch_alter_table("snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_snapshots_content_hash"), ["content_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_snapshots_monitored_url_id"), ["monitored_url_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_snapshots_monitored_url_id"))
        batch_op.drop_index(batch_op.f("ix_snapshots_content_hash"))

    op.drop_table("snapshots")
    op.drop_table("monitored_urls")
    # ### end Alembic commands ###
